name: Publish to VS Code Marketplace
on:
  push:
    branches: [main, fix/readable-stream-error]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SESSIONS_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
          envkey_CLIENT_IDENTIFIER: com.pullflow.vscode
          envkey_PULLFLOW_APP_URL: https://app.pullflow.com
          envkey_PULLFLOW_TELEMETRY_URL: https://collector.pullflow.cloud

      - name: Install polyfill for ReadableStream
        run: npm install readable-stream

      - name: Build, compile and test
        run: |
          yarn
          yarn compile
          yarn lint
          yarn test

      - name: publish
        run: |
          yarn global add vsce
          vsce publish -p ${{ secrets.VSCE_ACCESS_TOKEN_TEMPORARY }}
