name: Publish to VS Code Marketplace
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SESSIONS_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
          envkey_CLIENT_IDENTIFIER: com.pullflow.vscode
          envkey_PULLFLOW_APP_URL: https://app.pullflow.com
          envkey_PULLFLOW_TELEMETRY_URL: https://collector.pullflow.cloud

      - name: Build, compile and test
        run: |
          yarn
          yarn compile
          yarn lint
          yarn test

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_ACCESS_TOKEN }}
        run: |
          npx @vscode/vsce publish -p "$VSCE_PAT"
